// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC53QppssHaxNYleVFi4ws_fROXZDaTIx4',
    appId: '1:242455858179:web:a7cd89c15d6cc5382cd236',
    messagingSenderId: '242455858179',
    projectId: 'application-9ea3b',
    authDomain: 'application-9ea3b.firebaseapp.com',
    databaseURL: 'https://application-9ea3b-default-rtdb.firebaseio.com',
    storageBucket: 'application-9ea3b.firebasestorage.app',
    measurementId: 'G-EXKX3LWBRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfpHWMdh5mjX-fAouiIEzDeVIX3DSSahw',
    appId: '1:242455858179:android:eb99f6b1cbfa086e2cd236',
    messagingSenderId: '242455858179',
    projectId: 'application-9ea3b',
    databaseURL: 'https://application-9ea3b-default-rtdb.firebaseio.com',
    storageBucket: 'application-9ea3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS9D56tYdfFISGCg55c5SqHCgwUWoH18g',
    appId: '1:242455858179:ios:bd86709566cb20f12cd236',
    messagingSenderId: '242455858179',
    projectId: 'application-9ea3b',
    databaseURL: 'https://application-9ea3b-default-rtdb.firebaseio.com',
    storageBucket: 'application-9ea3b.firebasestorage.app',
    androidClientId: '242455858179-vnlcrph3nn5mf8j04u0077ku7c6bud46.apps.googleusercontent.com',
    iosClientId: '242455858179-9h1bgatba0sbjt5i2qtj4gfa02agis6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS9D56tYdfFISGCg55c5SqHCgwUWoH18g',
    appId: '1:242455858179:ios:bd86709566cb20f12cd236',
    messagingSenderId: '242455858179',
    projectId: 'application-9ea3b',
    databaseURL: 'https://application-9ea3b-default-rtdb.firebaseio.com',
    storageBucket: 'application-9ea3b.firebasestorage.app',
    androidClientId: '242455858179-vnlcrph3nn5mf8j04u0077ku7c6bud46.apps.googleusercontent.com',
    iosClientId: '242455858179-9h1bgatba0sbjt5i2qtj4gfa02agis6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC53QppssHaxNYleVFi4ws_fROXZDaTIx4',
    appId: '1:242455858179:web:8d8b40167260f6712cd236',
    messagingSenderId: '242455858179',
    projectId: 'application-9ea3b',
    authDomain: 'application-9ea3b.firebaseapp.com',
    databaseURL: 'https://application-9ea3b-default-rtdb.firebaseio.com',
    storageBucket: 'application-9ea3b.firebasestorage.app',
    measurementId: 'G-8341KRTZJ3',
  );

}